// resources/js/components/LoginComponent.vue
<template>
    <div>
        <div class="container">
            <form method="POST" v-on:submit.prevent="onSubmit">

                <input type="text" v-model="username" v-bind:placeholder="$t('message.username')" required>
                <span v-model="usernameErrors">{{ usernameErrors }}</span>
                <br>
                <input type="password" v-model="password" v-bind:placeholder="$t('message.password')" required>
                <span v-model="passwordErrors">{{ passwordErrors }}</span>
                <br>
                <button type="submit">{{ $t('message.login') }}</button>
            </form>
        </div>
    </div>
</template>

<script>
    export default {
        data: function () {
            return {
                username: '',
                password: '',
                usernameErrors: '',
                passwordErrors: ''
            }
        },

        methods: {
            onSubmit: function (event) {
                let self = this
                let formData = new FormData()
                formData.append('username', this.username)
                formData.append('password', this.password)
                formData.append('_token', self.csrf)
                this.usernameErrors = ''
                this.passwordErrors = ''

                axios.post('login', formData)
                    .then(function (response) {
                        self.$router.push('products')
                    })
                    .catch(function (error) {
                        console.log(error.response.data)
                        if (error.response.data.errors.hasOwnProperty('username')) {
                            self.usernameErrors = error.response.data.errors.username[0]
                        }
                        if (error.response.data.errors.hasOwnProperty('password')) {
                            self.passwordErrors = error.response.data.errors.password[0]
                        }
                    })
            }
        },

        computed: {
            csrf: function () {
                return document.querySelector('meta[name="csrf-token"]').getAttribute('content')
            }
        }
    }
</script>

// resources/js/react-components/Login.jsx
import React, { Component } from 'react'
import ReactDOM from 'react-dom'
import axios from 'axios'

export default class Login extends Component {
    state = {
        username: [],
        password: '',
        usernameError: '',
        passwordError: ''
    }

    handleInputChange = (event) => {
        const target = event.target
        const value = target.value
        const name = target.name
        this.setState({
            [name]: value
        })
    }

    handleSubmit = (event) => {
        event.preventDefault()
        let self = this
        let formData = new FormData()
        formData.append('username', this.state.username)
        formData.append('password', this.state.password)

        this.setState({ usernameError: '' })
        this.setState({ passwordError: '' })

        axios.post('/login', formData)
            .then(function (response) {
                console.log('Redirect!!!')
            })
            .catch(function (error) {

                if (error.response.data.errors.hasOwnProperty('username')) {
                    self.setState({ usernameError: error.response.data.errors.username[0] })
                }
                if (error.response.data.errors.hasOwnProperty('password')) {
                    self.setState({ passwordError: error.response.data.errors.password[0] })
                }
            })
    }

    render () {
        return (
            <div className="container">
                <form onSubmit={this.handleSubmit}>
                    <input type="text" name="username" placeholder="Username" value={this.state.username}
                           onChange={this.handleInputChange} required/>
                    <span className="validation-username-error">{this.state.usernameError}</span>
                    <br/>
                    <input type="password" name="password" placeholder="Password"
                           value={this.state.password} onChange={this.handleInputChange} required/>
                    <span className="validation-password-error">{this.state.passwordError}</span>
                    <br/>
                    <button type="submit">Login</button>
                </form>
            </div>
        )
    }
}

if (document.getElementById('login')) {
    ReactDOM.render(<Login/>, document.getElementById('login'))
}
