// resources/js/components/ProductFormComponent.vue
<template>
    <div>
        <div class="container">
            <form method="POST"  v-on:submit.prevent="onSubmit" >
                <input type="text" v-model="title" placeholder="Title" value="title" required>
                <span v-model="titleErrors">{{ titleErrors }}</span>
                <br>
                <input type="text" v-model="description" placeholder="Description" value="description" required>
                <span v-model="descriptionErrors">{{ descriptionErrors }}</span>
                <br>
                <input type="text" v-model="price" placeholder="Price" value="price" required>
                <span v-model="priceErrors">{{ priceErrors }}</span>
                <br>
                <input type="file" @change="onFileChanged"/>
                <span v-model="imageErrors">{{ imageErrors }}</span>
                <br>
                <button type="submit">Save</button>
            </form>
            <br>
            <a href="#products">Products</a>
        </div>
    </div>
</template>

<script>
    export default {
        data: function () {
            return {
                title: '',
                description: '',
                price: '',
                image: null,
                titleErrors: '',
                descriptionErrors: '',
                priceErrors: '',
                imageErrors: ''
            }
        },

        mounted () {
            let self = this;
            axios
                .get('/product/' + this.$route.params.id)
                .then(function(response){
                    self.title = response.data.title,
                    self.description = response.data.description,
                    self.price = response.data.price
                })
                .catch(function (error) {
                    if (error.response.status === 404) {
                        console.log('Product does not exist')
                    }
                })
        },

        methods: {
            onFileChanged (event) {
                this.image = event.target.files[0]
            },

            onSubmit: function (event) {
                let self = this;
                let formData = new FormData();
                formData.append('title', this.title);
                formData.append('description', this.description);
                formData.append('price', this.price);
                formData.append('image', this.image);
                formData.append('_token', this.csrf);

                this.titleErrors = '';
                this.descriptionErrors = '';
                this.priceErrors = '';
                this.imageErrors = '';

                let postUrl = '/product/';
                if (this.$route.params.id) {
                    formData.append('_method', 'PATCH');
                    postUrl = '/product/' + this.$route.params.id;
                }

                axios.post(postUrl, formData,
                {
                    headers: {
                        'Content-Type': 'multipart/form-data'
                    }
                })
                .then(function (response) {
                    console.log(response.data);
                })
                .catch(function (error) {
                    if (error.response.status === 422) {
                        console.log(error.response.data.errors);
                        if (error.response.data.errors.hasOwnProperty('title')) {
                            self.titleErrors = error.response.data.errors.title[0];
                        }
                        if (error.response.data.errors.hasOwnProperty('description')) {
                            self.descriptionErrors = error.response.data.errors.description[0]
                        }
                        if (error.response.data.errors.hasOwnProperty('price')) {
                            self.priceErrors = error.response.data.errors.price[0]
                        }
                        if (error.response.data.errors.hasOwnProperty('image')) {
                            self.imageErrors = error.response.data.errors.image[0]
                        }
                    }
                })

            },
        },

        computed: {
            csrf: function () {
                return document.querySelector('meta[name="csrf-token"]').getAttribute('content');
            }
        }
    }
</script>

// resources/js/react-components/ProductForm.jsx
import React, { Component } from 'react'
import ReactDOM from 'react-dom'
import axios from 'axios'
import {
    BrowserRouter as Router,
    Route,
    Link
} from 'react-router-dom'

export default class ProductForm extends Component {
    state = {
        title: '',
        description: '',
        price: '',
        image: null,
        titleError: '',
        descriptionError: '',
        priceError: '',
        imageError: ''
    }

    componentDidMount () {
        let self = this;
        if (this.props.match.params.id) {
            axios
                .get('/product/' + self.props.match.params.id)
                .then(response => {
                    self.setState({
                        title: response.data.title,
                        description: response.data.description,
                        price: response.data.price
                    })
                })
        }
    }

    handleInputChange = (event) => {
        const target = event.target
        const value = target.value
        const name = target.name
        this.setState({
            [name]: value
        })
    }

    fileChangedHandler = (event) => {
        this.setState({ image: event.target.files[0] })
    }

    handleSubmit = (event) => {
        event.preventDefault()
        let self = this

        this.setState({ titleError: '' })
        this.setState({ descriptionError: '' })
        this.setState({ priceError: '' })
        this.setState({ imageError: '' })

        let formData = new FormData()
        formData.append('title', this.state.title)
        formData.append('description', this.state.description)
        formData.append('price', this.state.price)
        formData.append('image', this.state.image)

        let postUrl = '/product/'
        if (this.props.match.params.id) {
            formData.append('_method', 'PATCH')
            postUrl = '/product/' + this.props.match.params.id
        }

        axios.post(postUrl, formData,
            {
                headers: {
                    'Content-Type': 'multipart/form-data'
                }
            })
            .then(function (response) {
                console.log(response.data)
            })
            .catch(function (error) {
                if (error.response.status === 422) {
                    if (error.response.data.errors.hasOwnProperty('title')) {
                        self.setState({ titleError: error.response.data.errors.title[0] })
                    }
                    if (error.response.data.errors.hasOwnProperty('description')) {
                        self.setState({ descriptionError: error.response.data.errors.description[0] })
                    }
                    if (error.response.data.errors.hasOwnProperty('price')) {
                        self.setState({ priceError: error.response.data.errors.price[0] })
                    }
                    if (error.response.data.errors.hasOwnProperty('image')) {
                        self.setState({ imageError: error.response.data.errors.image[0] })
                    }
                }
            })
    }

    render () {
        return (
            <div className="container">
                <form method="POST" onSubmit={this.handleSubmit}>
                    <input type="text" name="title" placeholder="Title" value={this.state.title} onChange={this.handleInputChange} required/>
                    <span className="validation-title-error">{this.state.titleError}</span>
                    <br/>
                    <input type="text" name="description" placeholder="Description" value={this.state.description} onChange={this.handleInputChange} required/>
                    <span className="validation-description-error">{this.state.descriptionError}</span>
                    <br/>
                    <input type="text" name="price" placeholder="Price" value={this.state.price} onChange={this.handleInputChange} required/>
                    <span className="validation-price-error">{this.state.priceError}</span>
                    <br/>
                    <input type="file" name="image" onChange={this.fileChangedHandler} />
                    <span className="validation-image-error">{this.state.imageError}</span>
                    <br/>
                    <button type="submit">Save</button>
                </form>
                <br/>
                <a href="/react/products">Products</a>
            </div>
        )
    }
}
