// resources/js/components/ProductsComponent.vue
<template>
    <div>
        <div v-for="product in products" :key="product.id">
            <product v-bind:product="product"></product>
            <router-link :to="{ name: 'product', params: { id: product.id }}">{{ $t('message.edit') }}</router-link>
            <form method="POST">
                <button type="submit" v-on:click.prevent="deleteProduct(product.id)">{{ $t('message.delete') }}</button>
            </form>
            <hr>
        </div>
        <router-link to="/product">{{ $t('message.add') }}</router-link>
        <form id="frm-logout" v-on:submit.prevent="onSubmit">
            <button type="submit">{{ $t('message.logout') }}</button>
        </form>
    </div>
</template>

<script>
    var product = require('./ProductComponent.vue').default
    import mixin from '../mixin'
    export default {
        data: function () {
            return {
                products: [],
                _token: '',
                _method: 'DELETE'
            }
        },

        mixins: [mixin],

        mounted () {
            let self = this
            axios
                .get('/products')
                .then(response => {
                    console.log(response.data)
                    this.products = response.data
                }).catch(function (error) {
                if (error.response.status === 401) {
                    self.$router.push('login')
                }
            })
        },

        methods: {
            deleteProduct: function (id) {
                let self = this
                console.log(this.csrf)
                axios.delete('/products/' + id, {
                    _token: this.csrf,
                    _method: this.method
                })
                    .then(function (response) {
                        self.products = response.data
                    })
                    .catch(function (error) {
                        console.log(error)
                    })
            },

            onSubmit: function (event) {
                let self = this
                let formData = new FormData()
                formData.append('_token', this.csrf)

                axios.post('/logout', formData)
                    .then(function (response) {
                        self.$router.push('login')
                    })
                    .catch(function (error) {
                        console.log(error.response.data)
                    })
            }
        },

        components: {
            'product': product
        },
    }
</script>

// resources/js/react-components/Products.jsx
import React, { Component } from 'react'
import ReactDOM from 'react-dom'
import axios from 'axios'
import Product from './Product'
import Cart from './Cart'
import { Redirect, Link } from 'react-router-dom'

export default class Products extends Component {
    state = {
        products: [],
        isLoggedIn: true
    }

    componentDidMount () {
        let self = this
        axios
            .get('/products')
            .then(response => {
                this.setState({
                    products: response.data
                })
            }).catch(function (error) {
            if (error.response.status === 401) {
                self.setState({ isLoggedIn: false })
            }
        })
    }

    addProduct = (event, id) => {
        event.preventDefault()
        axios
            .get('/' + id)
            .then(response => {
                this.setState({ products: response.data })
            })
    }

    handleDeleteProduct = (event, id) => {
        event.preventDefault()
        let self = this
        let formData = new FormData()
        formData.append('_method', 'DELETE')
        axios.delete('/products/' + id, formData)
            .then(function (response) {
                self.setState({ products: response.data })
            })
            .catch(function (error) {
                console.log(error)
            })
    }

    handleDeleteLogout = (event, id) => {
        event.preventDefault()
        let self = this
        axios.post('/logout')
            .then(function (response) {
                self.setState({ isLoggedIn: false })
            })
            .catch(function (error) {
                console.log(error)
            })
    }

    render () {
        if (this.state.isLoggedIn == false) {
            return <Redirect to={{ pathname: '/login' }}/>
        }

        const { products } = this.state

        const result = products.map((product) => {
            return (
                <div key={product.id}>
                    <Product product={product}/>
                    <Link to={'/product/' + product.id}>Edit</Link>
                    <form method="POST" onSubmit={(e) => this.handleDeleteProduct(e, product.id)}>
                        <button type="submit">Delete Product</button>
                    </form>
                    <hr/>
                </div>
            )
        })

        return (
            <div className="container">
                {result}

                <Link to={'/product'}>Add</Link>

                <form method="POST" onSubmit={this.handleDeleteLogout}>
                    <button type="submit">Logout</button>
                </form>
            </div>
        )
    }
}
