// resources/js/react-components/Order.jsx
import React, { Component } from 'react'
import ReactDOM from 'react-dom'
import axios from 'axios'
import Product from './Product'
import Cart from './Cart'
import { withTranslation, Trans } from 'react-i18next'
import { Link, Redirect } from 'react-router-dom'

class Order extends Component {
    state = {
        order: [],
        products: [],
        isLoggedIn: true
    }

    componentDidMount () {
        let self = this
        axios
            .get('/order/' + this.props.match.params.id)
            .then(response => {
                self.setState({
                    order: response.data.order,
                    products: response.data.products
                })
                var totalPrice = 0
                for (var product in self.state.products) {
                    totalPrice += parseFloat(self.state.products[product].price)
                }
                var orderCopy = self.state.order;
                orderCopy['totalPrice'] = totalPrice;
                self.setState({
                    order: orderCopy,
                })
            })
            .catch(function (error) {
                if (error.response.status === 401) {
                    self.setState({ isLoggedIn: false })
                }
            })
    }

    render () {
        if (this.state.isLoggedIn == false) {
            return <Redirect to={{ pathname: '/login' }}/>
        }

        const { order } = this.state
        const { products } = this.state

        const result = products.map((product) => {
            return (
                <div key={product.id}>
                    <Product product={product}/>
                </div>
            )
        })

        return (
            <div className="container">
                <div>
                    {order.name}
                    <br/>
                    {order.contact_details}
                    <br/>
                    {order.comments}
                    <br/>
                    {order.totalPrice}
                    <br/>
                    {order.created_at}
                    <br/><br/>
                    {result}
                    <Link to={'../orders/'}>{this.props.t('goToOrders')}</Link>
                </div>
            </div>
        )
    }
}
export default withTranslation('common')(Order)

// resources/js/components/OrderComponent.vue
<template>
    <div>
        <div class="container">
            <div>
                {{ order.name }}
                <br>
                {{ order.contact_details }}
                <br>
                {{ order.comments }}
                <br>
                {{ order.totalPrice }}
                <br>
                {{ order.created_at }}
                <br><br>
                <div v-for="product in products" :key="product.id">
                    <product v-bind:product="product"></product>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    var product = require('./ProductComponent.vue').default
    export default {
        data: function () {
            return {
                order: [],
                products: []
            }
        },

        mounted () {
            let self = this
            axios
                .get('/order/' + this.$route.params.id)
                .then(response => {

                    this.order = response.data.order
                    this.products = response.data.products

                    var totalPrice = 0
                    for (var product in this.products) {
                        totalPrice += parseFloat(this.products[product].price)
                    }
                    this.order['totalPrice'] = totalPrice
                })
                .catch(function (error) {
                    if (error.response.status === 401) {
                        self.$router.push('/login')
                    }
                })
        },
        components: {
            'product': product
        },
    }
</script>
