// resources/js/react-components/Product.jsx
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
export default class Product extends Component {
    state = {
        url: window.location.hostname
    };

    render() {
        return (
            <div className="product">
                <div className="product-image">
                    <img src={window.location.protocol + '//' + this.state.url + ':' + window.location.port + '/storage/images/' + this.props.product.image_name}/>
                </div>
                <div className="product-info">
                    <p> { this.props.product.id } </p>
                    <p> { this.props.product.title } </p>
                    <p> { this.props.product.description } </p>
                    <p> { this.props.product.price } </p>
                </div>
            </div>
        );
    }
}

// resources/js/components/ProductComponent.vue
<template>
    <div>
        <div class="product">
            <div class="product-image">
                <img v-bind:src="baseUrl + '/storage/images/' + product.image_name">
            </div>
            <div class="product-info">
                <p> {{ product.id }} </p>
                <p> {{ product.title }} </p>
                <p> {{ product.description }} </p>
                <p> {{ product.price }} </p>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        props: ['product'],
        computed: {
            baseUrl: function () {
                return window.location.origin;
            }
        }
    }
</script>
